### ISSUE TITLE
Set timeout for idle sockets

### ISSUE THREAD

**Issue by luisviman** [cwysong85/msrp-node-lib#14]
* The timeout interval must be configurable by setting the new `socketTimeout` parameter in the `msrp.js` configuration file.
* Default `socketTimeout` should be 60 minutes.
* Sockets timeout can be disable by setting `socketTimeout` to 0.

**Comment by cwysong85** [comment]
@luisviman Something just occurred to me. I think we should set the default to 60 mins. Because this is more of a "catch all" if all else fails type of scenario. We do want sockets to close eventually, but maybe not as fast as 20 mins. Heartbeats and other mechanism should be closing down the session quicker. For instance, an application may want to control it's own internal "idle/no data" mechanism. A higher default socket timeout will work better for all applications. This is why NodeJS sets this to "null" by default because they don't want to close down sockets on behalf of an application.

**Comment by luisviman** [comment]
OK, @cwysong85 , I'm setting the default value to 60 minutes.

**Comment by luisviman** [comment]
`socketTimeout` will be disabled by default. This feature will be included in msrp-node-lib 0.0.31.
